inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7.1
  TargetRailsVersion: 6.0.3.4
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'lib/tasks/*'
    - 'tmp/**/*'
    - 'db/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Rails:
  Enabled: true

Rails/FilePath:
  Exclude:
    - 'spec/rails_helper.rb'
# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# クラスのコメント必須を無視
Documentation:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# 文字リテラルのイミュータブル宣言を無視（freezeになるのはRuby3以降）
Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 25

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleExpectations:
  Max: 2

RSpec/InstanceVariable:
  AssignmentOnly: true

Metrics/AbcSize:
  Max: 20